name: cs769
channels:
  - conda-forge
dependencies:
  - python < 3.12
  - mosestokenizer
  - tqdm
  - pytorch
  - fairseq
  - stanza
  - pip
  - pip:
    - subword-nmt
    - indic-nlp-library
    - torchvision
    - torchaudio
