name: cs769
channels:
  - conda-forge
dependencies:
  - python < 3.12
  - mosestokenizer
  - tqdm
  - pytorch
  - fairseq
  - stanza
  - tqdm
  - pip
  - sacremoses
  - numpy < 1.24
  - pip:
    - compare-mt
    - numpy < 1.24
    - subword-nmt
    - indic-nlp-library
    - torchvision
    - torchaudio
